export const browserCoreExamples = [
  "xclaw browser status",
  "xclaw browser start",
  "xclaw browser stop",
  "xclaw browser tabs",
  "xclaw browser open https://example.com",
  "xclaw browser focus abcd1234",
  "xclaw browser close abcd1234",
  "xclaw browser screenshot",
  "xclaw browser screenshot --full-page",
  "xclaw browser screenshot --ref 12",
  "xclaw browser snapshot",
  "xclaw browser snapshot --format aria --limit 200",
  "xclaw browser snapshot --efficient",
  "xclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "xclaw browser navigate https://example.com",
  "xclaw browser resize 1280 720",
  "xclaw browser click 12 --double",
  'xclaw browser type 23 "hello" --submit',
  "xclaw browser press Enter",
  "xclaw browser hover 44",
  "xclaw browser drag 10 11",
  "xclaw browser select 9 OptionA OptionB",
  "xclaw browser upload /tmp/xclaw/uploads/file.pdf",
  'xclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "xclaw browser dialog --accept",
  'xclaw browser wait --text "Done"',
  "xclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "xclaw browser console --level error",
  "xclaw browser pdf",
];
